filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      include_labels:
        - "co.elastic.logs/module"

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
