filebeat.modules:
- module: apache
  # Access logs
  access:
    enabled: true
    var.paths: ["/mnt/httpd-logs/access_log"]

  # Error logs
  error:
    enabled: true
    var.paths: ["/mnt/httpd-logs/error_log"]
  
- module: mysql
  # Error logs
  error:
    enabled: true
    var.paths: ["/mnt/db-logs/mysql-error.log"]

  # Slow logs
  slowlog:
    enabled: true
    var.paths: ["/mnt/db-logs/mysql-slow.log"]

filebeat.inputs:
# Spring Boot Application Logs
- type: log
  enabled: true
  paths:
    - /mnt/app-logs/*.log
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after
  processors:
    - script:
        lang: javascript
        source: >
          function process(event) {
              var message = event.Get("message");
              if (message != null) {
                  event.Put("message", message.replace(/\s+/g, " "));
              }
          }
    - dissect:
        tokenizer: "%{@timestamp} %{+@timestamp} %{log.level} %{process.id} --- [%{thread}] %{logger.name} : %{message}"
        field: "message"
        target_prefix: ""
        overwrite_keys: true
    - add_fields:
        target: "event"
        fields:
          dataset: "springboot.logs"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "elastic"

setup.kibana:
  host: "kibana:5601"